# Generated by Django 3.0.5 on 2021-12-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
                ('isVegetarian', models.BooleanField()),
                ('diets', models.IntegerField()),
            ],
        ),
    ]
