# Generated by Django 2.2.25 on 2022-01-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaPizzaApp', '0003_auto_20220104_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='nombre',
            field=models.CharField(default='default', max_length=50, unique=True),
        ),
    ]
