# Generated by Django 2.2.25 on 2022-01-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaPizzaApp', '0004_auto_20220111_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='nombre',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
